// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.8
// source: ens/ens.proto

package pbEns

import (
	order "Open_IM/pkg/proto/order"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RollbackENSRegisterTxnReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OperationID     string `protobuf:"bytes,1,opt,name=OperationID,proto3" json:"OperationID,omitempty"`
	RegisterTxnHash string `protobuf:"bytes,2,opt,name=RegisterTxnHash,proto3" json:"RegisterTxnHash,omitempty"`
}

func (x *RollbackENSRegisterTxnReq) Reset() {
	*x = RollbackENSRegisterTxnReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ens_ens_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RollbackENSRegisterTxnReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackENSRegisterTxnReq) ProtoMessage() {}

func (x *RollbackENSRegisterTxnReq) ProtoReflect() protoreflect.Message {
	mi := &file_ens_ens_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackENSRegisterTxnReq.ProtoReflect.Descriptor instead.
func (*RollbackENSRegisterTxnReq) Descriptor() ([]byte, []int) {
	return file_ens_ens_proto_rawDescGZIP(), []int{0}
}

func (x *RollbackENSRegisterTxnReq) GetOperationID() string {
	if x != nil {
		return x.OperationID
	}
	return ""
}

func (x *RollbackENSRegisterTxnReq) GetRegisterTxnHash() string {
	if x != nil {
		return x.RegisterTxnHash
	}
	return ""
}

type RollbackENSRegisterTxnResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommonResp *CommonResp `protobuf:"bytes,1,opt,name=CommonResp,proto3" json:"CommonResp,omitempty"`
}

func (x *RollbackENSRegisterTxnResp) Reset() {
	*x = RollbackENSRegisterTxnResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ens_ens_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RollbackENSRegisterTxnResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackENSRegisterTxnResp) ProtoMessage() {}

func (x *RollbackENSRegisterTxnResp) ProtoReflect() protoreflect.Message {
	mi := &file_ens_ens_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackENSRegisterTxnResp.ProtoReflect.Descriptor instead.
func (*RollbackENSRegisterTxnResp) Descriptor() ([]byte, []int) {
	return file_ens_ens_proto_rawDescGZIP(), []int{1}
}

func (x *RollbackENSRegisterTxnResp) GetCommonResp() *CommonResp {
	if x != nil {
		return x.CommonResp
	}
	return nil
}

type ConfirmEnsOrderHasBeenRegisteredReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OperationID     string `protobuf:"bytes,1,opt,name=OperationID,proto3" json:"OperationID,omitempty"`
	RegisterTxnHash string `protobuf:"bytes,2,opt,name=RegisterTxnHash,proto3" json:"RegisterTxnHash,omitempty"`
}

func (x *ConfirmEnsOrderHasBeenRegisteredReq) Reset() {
	*x = ConfirmEnsOrderHasBeenRegisteredReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ens_ens_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfirmEnsOrderHasBeenRegisteredReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmEnsOrderHasBeenRegisteredReq) ProtoMessage() {}

func (x *ConfirmEnsOrderHasBeenRegisteredReq) ProtoReflect() protoreflect.Message {
	mi := &file_ens_ens_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmEnsOrderHasBeenRegisteredReq.ProtoReflect.Descriptor instead.
func (*ConfirmEnsOrderHasBeenRegisteredReq) Descriptor() ([]byte, []int) {
	return file_ens_ens_proto_rawDescGZIP(), []int{2}
}

func (x *ConfirmEnsOrderHasBeenRegisteredReq) GetOperationID() string {
	if x != nil {
		return x.OperationID
	}
	return ""
}

func (x *ConfirmEnsOrderHasBeenRegisteredReq) GetRegisterTxnHash() string {
	if x != nil {
		return x.RegisterTxnHash
	}
	return ""
}

type ConfirmEnsOrderHasBeenRegisteredResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommonResp *CommonResp `protobuf:"bytes,1,opt,name=CommonResp,proto3" json:"CommonResp,omitempty"`
}

func (x *ConfirmEnsOrderHasBeenRegisteredResp) Reset() {
	*x = ConfirmEnsOrderHasBeenRegisteredResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ens_ens_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfirmEnsOrderHasBeenRegisteredResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmEnsOrderHasBeenRegisteredResp) ProtoMessage() {}

func (x *ConfirmEnsOrderHasBeenRegisteredResp) ProtoReflect() protoreflect.Message {
	mi := &file_ens_ens_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmEnsOrderHasBeenRegisteredResp.ProtoReflect.Descriptor instead.
func (*ConfirmEnsOrderHasBeenRegisteredResp) Descriptor() ([]byte, []int) {
	return file_ens_ens_proto_rawDescGZIP(), []int{3}
}

func (x *ConfirmEnsOrderHasBeenRegisteredResp) GetCommonResp() *CommonResp {
	if x != nil {
		return x.CommonResp
	}
	return nil
}

type ConfirmEnsOrderHasBeenPaidReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OperationID string `protobuf:"bytes,1,opt,name=OperationID,proto3" json:"OperationID,omitempty"`
	OrderId     string `protobuf:"bytes,2,opt,name=OrderId,proto3" json:"OrderId,omitempty"`
	TxnHash     string `protobuf:"bytes,3,opt,name=TxnHash,proto3" json:"TxnHash,omitempty"`
}

func (x *ConfirmEnsOrderHasBeenPaidReq) Reset() {
	*x = ConfirmEnsOrderHasBeenPaidReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ens_ens_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfirmEnsOrderHasBeenPaidReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmEnsOrderHasBeenPaidReq) ProtoMessage() {}

func (x *ConfirmEnsOrderHasBeenPaidReq) ProtoReflect() protoreflect.Message {
	mi := &file_ens_ens_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmEnsOrderHasBeenPaidReq.ProtoReflect.Descriptor instead.
func (*ConfirmEnsOrderHasBeenPaidReq) Descriptor() ([]byte, []int) {
	return file_ens_ens_proto_rawDescGZIP(), []int{4}
}

func (x *ConfirmEnsOrderHasBeenPaidReq) GetOperationID() string {
	if x != nil {
		return x.OperationID
	}
	return ""
}

func (x *ConfirmEnsOrderHasBeenPaidReq) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ConfirmEnsOrderHasBeenPaidReq) GetTxnHash() string {
	if x != nil {
		return x.TxnHash
	}
	return ""
}

type ConfirmEnsOrderHasBeenPaidResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommonResp *CommonResp `protobuf:"bytes,1,opt,name=CommonResp,proto3" json:"CommonResp,omitempty"`
}

func (x *ConfirmEnsOrderHasBeenPaidResp) Reset() {
	*x = ConfirmEnsOrderHasBeenPaidResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ens_ens_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfirmEnsOrderHasBeenPaidResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmEnsOrderHasBeenPaidResp) ProtoMessage() {}

func (x *ConfirmEnsOrderHasBeenPaidResp) ProtoReflect() protoreflect.Message {
	mi := &file_ens_ens_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmEnsOrderHasBeenPaidResp.ProtoReflect.Descriptor instead.
func (*ConfirmEnsOrderHasBeenPaidResp) Descriptor() ([]byte, []int) {
	return file_ens_ens_proto_rawDescGZIP(), []int{5}
}

func (x *ConfirmEnsOrderHasBeenPaidResp) GetCommonResp() *CommonResp {
	if x != nil {
		return x.CommonResp
	}
	return nil
}

type GetEnsOrderInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OperationID string `protobuf:"bytes,1,opt,name=OperationID,proto3" json:"OperationID,omitempty"`
	UserId      string `protobuf:"bytes,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	OrderId     uint64 `protobuf:"varint,3,opt,name=OrderId,proto3" json:"OrderId,omitempty"`
}

func (x *GetEnsOrderInfoReq) Reset() {
	*x = GetEnsOrderInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ens_ens_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetEnsOrderInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEnsOrderInfoReq) ProtoMessage() {}

func (x *GetEnsOrderInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_ens_ens_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEnsOrderInfoReq.ProtoReflect.Descriptor instead.
func (*GetEnsOrderInfoReq) Descriptor() ([]byte, []int) {
	return file_ens_ens_proto_rawDescGZIP(), []int{6}
}

func (x *GetEnsOrderInfoReq) GetOperationID() string {
	if x != nil {
		return x.OperationID
	}
	return ""
}

func (x *GetEnsOrderInfoReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetEnsOrderInfoReq) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type EnsOrderInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderId         uint64 `protobuf:"varint,1,opt,name=OrderId,proto3" json:"OrderId,omitempty"`
	EnsName         string `protobuf:"bytes,2,opt,name=EnsName,proto3" json:"EnsName,omitempty"`
	Status          string `protobuf:"bytes,3,opt,name=Status,proto3" json:"Status,omitempty"`
	TxnType         string `protobuf:"bytes,4,opt,name=TxnType,proto3" json:"TxnType,omitempty"`
	USDPrice        uint64 `protobuf:"varint,5,opt,name=USDPrice,proto3" json:"USDPrice,omitempty"`
	USDGasFee       uint64 `protobuf:"varint,6,opt,name=USDGasFee,proto3" json:"USDGasFee,omitempty"`
	EnsInviter      string `protobuf:"bytes,7,opt,name=EnsInviter,proto3" json:"EnsInviter,omitempty"`
	TxnHash         string `protobuf:"bytes,8,opt,name=TxnHash,proto3" json:"TxnHash,omitempty"`
	RegisterTxnHash string `protobuf:"bytes,9,opt,name=RegisterTxnHash,proto3" json:"RegisterTxnHash,omitempty"`
	CreateTime      string `protobuf:"bytes,10,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"`
	PayTime         string `protobuf:"bytes,11,opt,name=PayTime,proto3" json:"PayTime,omitempty"`
	ExpireTime      string `protobuf:"bytes,12,opt,name=ExpireTime,proto3" json:"ExpireTime,omitempty"`
}

func (x *EnsOrderInfo) Reset() {
	*x = EnsOrderInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ens_ens_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnsOrderInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsOrderInfo) ProtoMessage() {}

func (x *EnsOrderInfo) ProtoReflect() protoreflect.Message {
	mi := &file_ens_ens_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnsOrderInfo.ProtoReflect.Descriptor instead.
func (*EnsOrderInfo) Descriptor() ([]byte, []int) {
	return file_ens_ens_proto_rawDescGZIP(), []int{7}
}

func (x *EnsOrderInfo) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *EnsOrderInfo) GetEnsName() string {
	if x != nil {
		return x.EnsName
	}
	return ""
}

func (x *EnsOrderInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *EnsOrderInfo) GetTxnType() string {
	if x != nil {
		return x.TxnType
	}
	return ""
}

func (x *EnsOrderInfo) GetUSDPrice() uint64 {
	if x != nil {
		return x.USDPrice
	}
	return 0
}

func (x *EnsOrderInfo) GetUSDGasFee() uint64 {
	if x != nil {
		return x.USDGasFee
	}
	return 0
}

func (x *EnsOrderInfo) GetEnsInviter() string {
	if x != nil {
		return x.EnsInviter
	}
	return ""
}

func (x *EnsOrderInfo) GetTxnHash() string {
	if x != nil {
		return x.TxnHash
	}
	return ""
}

func (x *EnsOrderInfo) GetRegisterTxnHash() string {
	if x != nil {
		return x.RegisterTxnHash
	}
	return ""
}

func (x *EnsOrderInfo) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *EnsOrderInfo) GetPayTime() string {
	if x != nil {
		return x.PayTime
	}
	return ""
}

func (x *EnsOrderInfo) GetExpireTime() string {
	if x != nil {
		return x.ExpireTime
	}
	return ""
}

type GetEnsOrderInfoResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommonResp   *CommonResp         `protobuf:"bytes,1,opt,name=CommonResp,proto3" json:"CommonResp,omitempty"`
	EnsOrderInfo *EnsOrderInfo       `protobuf:"bytes,2,opt,name=EnsOrderInfo,proto3" json:"EnsOrderInfo,omitempty"`
	ScanTaskInfo *order.ScanTaskInfo `protobuf:"bytes,3,opt,name=ScanTaskInfo,proto3" json:"ScanTaskInfo,omitempty"`
}

func (x *GetEnsOrderInfoResp) Reset() {
	*x = GetEnsOrderInfoResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ens_ens_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetEnsOrderInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEnsOrderInfoResp) ProtoMessage() {}

func (x *GetEnsOrderInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_ens_ens_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEnsOrderInfoResp.ProtoReflect.Descriptor instead.
func (*GetEnsOrderInfoResp) Descriptor() ([]byte, []int) {
	return file_ens_ens_proto_rawDescGZIP(), []int{8}
}

func (x *GetEnsOrderInfoResp) GetCommonResp() *CommonResp {
	if x != nil {
		return x.CommonResp
	}
	return nil
}

func (x *GetEnsOrderInfoResp) GetEnsOrderInfo() *EnsOrderInfo {
	if x != nil {
		return x.EnsOrderInfo
	}
	return nil
}

func (x *GetEnsOrderInfoResp) GetScanTaskInfo() *order.ScanTaskInfo {
	if x != nil {
		return x.ScanTaskInfo
	}
	return nil
}

type CreateRegisterEnsOrderReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OperationID string `protobuf:"bytes,1,opt,name=OperationID,proto3" json:"OperationID,omitempty"`
	UserId      string `protobuf:"bytes,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	EnsName     string `protobuf:"bytes,3,opt,name=EnsName,proto3" json:"EnsName,omitempty"`
	TxnType     string `protobuf:"bytes,4,opt,name=TxnType,proto3" json:"TxnType,omitempty"` // ETH  BNB  ERC20_BIU ERC20_USDT
	EnsInviter  string `protobuf:"bytes,5,opt,name=EnsInviter,proto3" json:"EnsInviter,omitempty"`
}

func (x *CreateRegisterEnsOrderReq) Reset() {
	*x = CreateRegisterEnsOrderReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ens_ens_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRegisterEnsOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRegisterEnsOrderReq) ProtoMessage() {}

func (x *CreateRegisterEnsOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_ens_ens_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRegisterEnsOrderReq.ProtoReflect.Descriptor instead.
func (*CreateRegisterEnsOrderReq) Descriptor() ([]byte, []int) {
	return file_ens_ens_proto_rawDescGZIP(), []int{9}
}

func (x *CreateRegisterEnsOrderReq) GetOperationID() string {
	if x != nil {
		return x.OperationID
	}
	return ""
}

func (x *CreateRegisterEnsOrderReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateRegisterEnsOrderReq) GetEnsName() string {
	if x != nil {
		return x.EnsName
	}
	return ""
}

func (x *CreateRegisterEnsOrderReq) GetTxnType() string {
	if x != nil {
		return x.TxnType
	}
	return ""
}

func (x *CreateRegisterEnsOrderReq) GetEnsInviter() string {
	if x != nil {
		return x.EnsInviter
	}
	return ""
}

type CreateRegisterEnsOrderResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommonResp   *CommonResp         `protobuf:"bytes,1,opt,name=CommonResp,proto3" json:"CommonResp,omitempty"`
	EnsOrderInfo *EnsOrderInfo       `protobuf:"bytes,2,opt,name=EnsOrderInfo,proto3" json:"EnsOrderInfo,omitempty"`
	ScanTaskInfo *order.ScanTaskInfo `protobuf:"bytes,3,opt,name=ScanTaskInfo,proto3" json:"ScanTaskInfo,omitempty"`
}

func (x *CreateRegisterEnsOrderResp) Reset() {
	*x = CreateRegisterEnsOrderResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ens_ens_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRegisterEnsOrderResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRegisterEnsOrderResp) ProtoMessage() {}

func (x *CreateRegisterEnsOrderResp) ProtoReflect() protoreflect.Message {
	mi := &file_ens_ens_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRegisterEnsOrderResp.ProtoReflect.Descriptor instead.
func (*CreateRegisterEnsOrderResp) Descriptor() ([]byte, []int) {
	return file_ens_ens_proto_rawDescGZIP(), []int{10}
}

func (x *CreateRegisterEnsOrderResp) GetCommonResp() *CommonResp {
	if x != nil {
		return x.CommonResp
	}
	return nil
}

func (x *CreateRegisterEnsOrderResp) GetEnsOrderInfo() *EnsOrderInfo {
	if x != nil {
		return x.EnsOrderInfo
	}
	return nil
}

func (x *CreateRegisterEnsOrderResp) GetScanTaskInfo() *order.ScanTaskInfo {
	if x != nil {
		return x.ScanTaskInfo
	}
	return nil
}

type CommonResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrCode int32  `protobuf:"varint,1,opt,name=errCode,proto3" json:"errCode,omitempty"`
	ErrMsg  string `protobuf:"bytes,2,opt,name=errMsg,proto3" json:"errMsg,omitempty"`
}

func (x *CommonResp) Reset() {
	*x = CommonResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ens_ens_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommonResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonResp) ProtoMessage() {}

func (x *CommonResp) ProtoReflect() protoreflect.Message {
	mi := &file_ens_ens_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonResp.ProtoReflect.Descriptor instead.
func (*CommonResp) Descriptor() ([]byte, []int) {
	return file_ens_ens_proto_rawDescGZIP(), []int{11}
}

func (x *CommonResp) GetErrCode() int32 {
	if x != nil {
		return x.ErrCode
	}
	return 0
}

func (x *CommonResp) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

var File_ens_ens_proto protoreflect.FileDescriptor

var file_ens_ens_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x65, 0x6e, 0x73, 0x2f, 0x65, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x03, 0x65, 0x6e, 0x73, 0x1a, 0x1b, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x2f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x67, 0x0a, 0x19, 0x52, 0x6f, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x45, 0x4e, 0x53,
	0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x54, 0x78, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x20,
	0x0a, 0x0b, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44,
	0x12, 0x28, 0x0a, 0x0f, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x54, 0x78, 0x6e, 0x48,
	0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x54, 0x78, 0x6e, 0x48, 0x61, 0x73, 0x68, 0x22, 0x4d, 0x0a, 0x1a, 0x52, 0x6f,
	0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x45, 0x4e, 0x53, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65,
	0x72, 0x54, 0x78, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2f, 0x0a, 0x0a, 0x43, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x65,
	0x6e, 0x73, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x52, 0x0a, 0x43,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x22, 0x71, 0x0a, 0x23, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x72, 0x6d, 0x45, 0x6e, 0x73, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x48, 0x61, 0x73, 0x42,
	0x65, 0x65, 0x6e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x65, 0x64, 0x52, 0x65, 0x71,
	0x12, 0x20, 0x0a, 0x0b, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x49, 0x44, 0x12, 0x28, 0x0a, 0x0f, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x54, 0x78,
	0x6e, 0x48, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x65, 0x72, 0x54, 0x78, 0x6e, 0x48, 0x61, 0x73, 0x68, 0x22, 0x57, 0x0a, 0x24,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x45, 0x6e, 0x73, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x48,
	0x61, 0x73, 0x42, 0x65, 0x65, 0x6e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x65, 0x64,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x2f, 0x0a, 0x0a, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x65, 0x6e, 0x73, 0x2e, 0x43,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x52, 0x0a, 0x43, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x22, 0x75, 0x0a, 0x1d, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d,
	0x45, 0x6e, 0x73, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x48, 0x61, 0x73, 0x42, 0x65, 0x65, 0x6e, 0x50,
	0x61, 0x69, 0x64, 0x52, 0x65, 0x71, 0x12, 0x20, 0x0a, 0x0b, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x4f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x54, 0x78, 0x6e, 0x48, 0x61, 0x73, 0x68, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x54, 0x78, 0x6e, 0x48, 0x61, 0x73, 0x68, 0x22, 0x51, 0x0a, 0x1e,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x45, 0x6e, 0x73, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x48,
	0x61, 0x73, 0x42, 0x65, 0x65, 0x6e, 0x50, 0x61, 0x69, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2f,
	0x0a, 0x0a, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x65, 0x6e, 0x73, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x52, 0x0a, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x22,
	0x68, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x45, 0x6e, 0x73, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x20, 0x0a, 0x0b, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x4f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x18, 0x0a, 0x07, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x07, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x22, 0xec, 0x02, 0x0a, 0x0c, 0x45, 0x6e,
	0x73, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x45, 0x6e, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x45, 0x6e, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x54, 0x78, 0x6e, 0x54, 0x79, 0x70,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x54, 0x78, 0x6e, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x55, 0x53, 0x44, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x08, 0x55, 0x53, 0x44, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1c, 0x0a, 0x09,
	0x55, 0x53, 0x44, 0x47, 0x61, 0x73, 0x46, 0x65, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x09, 0x55, 0x53, 0x44, 0x47, 0x61, 0x73, 0x46, 0x65, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x45, 0x6e,
	0x73, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x45, 0x6e, 0x73, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x54, 0x78,
	0x6e, 0x48, 0x61, 0x73, 0x68, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x54, 0x78, 0x6e,
	0x48, 0x61, 0x73, 0x68, 0x12, 0x28, 0x0a, 0x0f, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x54, 0x78, 0x6e, 0x48, 0x61, 0x73, 0x68, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x54, 0x78, 0x6e, 0x48, 0x61, 0x73, 0x68, 0x12, 0x1e,
	0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x0a, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x50, 0x61, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x50, 0x61, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x45, 0x78, 0x70, 0x69,
	0x72, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x45, 0x78,
	0x70, 0x69, 0x72, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x22, 0xb6, 0x01, 0x0a, 0x13, 0x47, 0x65, 0x74,
	0x45, 0x6e, 0x73, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x2f, 0x0a, 0x0a, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x65, 0x6e, 0x73, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x52, 0x0a, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x35, 0x0a, 0x0c, 0x45, 0x6e, 0x73, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x6e, 0x66,
	0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x65, 0x6e, 0x73, 0x2e, 0x45, 0x6e,
	0x73, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0c, 0x45, 0x6e, 0x73, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x37, 0x0a, 0x0c, 0x53, 0x63, 0x61, 0x6e,
	0x54, 0x61, 0x73, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13,
	0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x53, 0x63, 0x61, 0x6e, 0x54, 0x61, 0x73, 0x6b, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x0c, 0x53, 0x63, 0x61, 0x6e, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x6e, 0x66,
	0x6f, 0x22, 0xa9, 0x01, 0x0a, 0x19, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x45, 0x6e, 0x73, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12,
	0x20, 0x0a, 0x0b, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49,
	0x44, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x45, 0x6e, 0x73,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x45, 0x6e, 0x73, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x54, 0x78, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x54, 0x78, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1e, 0x0a,
	0x0a, 0x45, 0x6e, 0x73, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x45, 0x6e, 0x73, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x72, 0x22, 0xbd, 0x01,
	0x0a, 0x1a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x45, 0x6e, 0x73, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2f, 0x0a, 0x0a,
	0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0f, 0x2e, 0x65, 0x6e, 0x73, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x52, 0x0a, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x35, 0x0a,
	0x0c, 0x45, 0x6e, 0x73, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x65, 0x6e, 0x73, 0x2e, 0x45, 0x6e, 0x73, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0c, 0x45, 0x6e, 0x73, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x37, 0x0a, 0x0c, 0x53, 0x63, 0x61, 0x6e, 0x54, 0x61, 0x73, 0x6b,
	0x49, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x2e, 0x53, 0x63, 0x61, 0x6e, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x0c, 0x53, 0x63, 0x61, 0x6e, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x3e, 0x0a,
	0x0a, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x65,
	0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x65, 0x72,
	0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x4d, 0x73, 0x67, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x72, 0x72, 0x4d, 0x73, 0x67, 0x32, 0x94, 0x02,
	0x0a, 0x0a, 0x65, 0x6e, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x59, 0x0a, 0x16,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x45, 0x6e,
	0x73, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x1e, 0x2e, 0x65, 0x6e, 0x73, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x45, 0x6e, 0x73, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x1f, 0x2e, 0x65, 0x6e, 0x73, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x45, 0x6e, 0x73, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x44, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x45, 0x6e,
	0x73, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x17, 0x2e, 0x65, 0x6e, 0x73,
	0x2e, 0x47, 0x65, 0x74, 0x45, 0x6e, 0x73, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x65, 0x71, 0x1a, 0x18, 0x2e, 0x65, 0x6e, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x45, 0x6e, 0x73,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x12, 0x65, 0x0a,
	0x1a, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x45, 0x6e, 0x73, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x48, 0x61, 0x73, 0x42, 0x65, 0x65, 0x6e, 0x50, 0x61, 0x69, 0x64, 0x12, 0x22, 0x2e, 0x65, 0x6e,
	0x73, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x45, 0x6e, 0x73, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x48, 0x61, 0x73, 0x42, 0x65, 0x65, 0x6e, 0x50, 0x61, 0x69, 0x64, 0x52, 0x65, 0x71, 0x1a,
	0x23, 0x2e, 0x65, 0x6e, 0x73, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x45, 0x6e, 0x73,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x48, 0x61, 0x73, 0x42, 0x65, 0x65, 0x6e, 0x50, 0x61, 0x69, 0x64,
	0x52, 0x65, 0x73, 0x70, 0x42, 0x1d, 0x5a, 0x1b, 0x4f, 0x70, 0x65, 0x6e, 0x5f, 0x49, 0x4d, 0x2f,
	0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x6e, 0x73, 0x3b, 0x70, 0x62,
	0x45, 0x6e, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ens_ens_proto_rawDescOnce sync.Once
	file_ens_ens_proto_rawDescData = file_ens_ens_proto_rawDesc
)

func file_ens_ens_proto_rawDescGZIP() []byte {
	file_ens_ens_proto_rawDescOnce.Do(func() {
		file_ens_ens_proto_rawDescData = protoimpl.X.CompressGZIP(file_ens_ens_proto_rawDescData)
	})
	return file_ens_ens_proto_rawDescData
}

var file_ens_ens_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_ens_ens_proto_goTypes = []interface{}{
	(*RollbackENSRegisterTxnReq)(nil),            // 0: ens.RollbackENSRegisterTxnReq
	(*RollbackENSRegisterTxnResp)(nil),           // 1: ens.RollbackENSRegisterTxnResp
	(*ConfirmEnsOrderHasBeenRegisteredReq)(nil),  // 2: ens.ConfirmEnsOrderHasBeenRegisteredReq
	(*ConfirmEnsOrderHasBeenRegisteredResp)(nil), // 3: ens.ConfirmEnsOrderHasBeenRegisteredResp
	(*ConfirmEnsOrderHasBeenPaidReq)(nil),        // 4: ens.ConfirmEnsOrderHasBeenPaidReq
	(*ConfirmEnsOrderHasBeenPaidResp)(nil),       // 5: ens.ConfirmEnsOrderHasBeenPaidResp
	(*GetEnsOrderInfoReq)(nil),                   // 6: ens.GetEnsOrderInfoReq
	(*EnsOrderInfo)(nil),                         // 7: ens.EnsOrderInfo
	(*GetEnsOrderInfoResp)(nil),                  // 8: ens.GetEnsOrderInfoResp
	(*CreateRegisterEnsOrderReq)(nil),            // 9: ens.CreateRegisterEnsOrderReq
	(*CreateRegisterEnsOrderResp)(nil),           // 10: ens.CreateRegisterEnsOrderResp
	(*CommonResp)(nil),                           // 11: ens.CommonResp
	(*order.ScanTaskInfo)(nil),                   // 12: order.ScanTaskInfo
}
var file_ens_ens_proto_depIdxs = []int32{
	11, // 0: ens.RollbackENSRegisterTxnResp.CommonResp:type_name -> ens.CommonResp
	11, // 1: ens.ConfirmEnsOrderHasBeenRegisteredResp.CommonResp:type_name -> ens.CommonResp
	11, // 2: ens.ConfirmEnsOrderHasBeenPaidResp.CommonResp:type_name -> ens.CommonResp
	11, // 3: ens.GetEnsOrderInfoResp.CommonResp:type_name -> ens.CommonResp
	7,  // 4: ens.GetEnsOrderInfoResp.EnsOrderInfo:type_name -> ens.EnsOrderInfo
	12, // 5: ens.GetEnsOrderInfoResp.ScanTaskInfo:type_name -> order.ScanTaskInfo
	11, // 6: ens.CreateRegisterEnsOrderResp.CommonResp:type_name -> ens.CommonResp
	7,  // 7: ens.CreateRegisterEnsOrderResp.EnsOrderInfo:type_name -> ens.EnsOrderInfo
	12, // 8: ens.CreateRegisterEnsOrderResp.ScanTaskInfo:type_name -> order.ScanTaskInfo
	9,  // 9: ens.ensService.CreateRegisterEnsOrder:input_type -> ens.CreateRegisterEnsOrderReq
	6,  // 10: ens.ensService.GetEnsOrderInfo:input_type -> ens.GetEnsOrderInfoReq
	4,  // 11: ens.ensService.ConfirmEnsOrderHasBeenPaid:input_type -> ens.ConfirmEnsOrderHasBeenPaidReq
	10, // 12: ens.ensService.CreateRegisterEnsOrder:output_type -> ens.CreateRegisterEnsOrderResp
	8,  // 13: ens.ensService.GetEnsOrderInfo:output_type -> ens.GetEnsOrderInfoResp
	5,  // 14: ens.ensService.ConfirmEnsOrderHasBeenPaid:output_type -> ens.ConfirmEnsOrderHasBeenPaidResp
	12, // [12:15] is the sub-list for method output_type
	9,  // [9:12] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_ens_ens_proto_init() }
func file_ens_ens_proto_init() {
	if File_ens_ens_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ens_ens_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RollbackENSRegisterTxnReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ens_ens_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RollbackENSRegisterTxnResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ens_ens_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfirmEnsOrderHasBeenRegisteredReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ens_ens_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfirmEnsOrderHasBeenRegisteredResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ens_ens_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfirmEnsOrderHasBeenPaidReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ens_ens_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfirmEnsOrderHasBeenPaidResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ens_ens_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetEnsOrderInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ens_ens_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnsOrderInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ens_ens_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetEnsOrderInfoResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ens_ens_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRegisterEnsOrderReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ens_ens_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRegisterEnsOrderResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ens_ens_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommonResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ens_ens_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ens_ens_proto_goTypes,
		DependencyIndexes: file_ens_ens_proto_depIdxs,
		MessageInfos:      file_ens_ens_proto_msgTypes,
	}.Build()
	File_ens_ens_proto = out.File
	file_ens_ens_proto_rawDesc = nil
	file_ens_ens_proto_goTypes = nil
	file_ens_ens_proto_depIdxs = nil
}
