#more prometheus-compose.yml 
global:
  scrape_interval:     15s 
  evaluation_interval: 15s 
  external_labels:
    monitor: 'openIM-monitor'

scrape_configs:
    - job_name: 'prometheus'
      static_configs:
      - targets: ['localhost:9091']

    - job_name: 'openIM-server'
      metrics_path: /metrics
      static_configs:
      - targets: ['localhost:10002']
        labels:
          group: 'api'

      - targets: ['localhost:20110']
        labels:
          group: 'user'

      - targets: ['localhost:20120']
        labels:
          group: 'friend'

      - targets: ['localhost:20130']
        labels:
          group: 'message'

      - targets: ['localhost:20140']
        labels:
          group: 'msg-gateway'    

      - targets: ['localhost:20150']
        labels:
          group: 'group'

      - targets: ['localhost:20160']
        labels:
          group: 'auth'

      - targets: ['localhost:20170']
        labels:
          group: 'push'

      - targets: ['localhost:20120']
        labels:
          group: 'friend'

      
      - targets: ['localhost:20230']
        labels:
          group: 'conversation' 

      
      - targets: ['localhost:21400', 'localhost:21401', 'localhost:21402', 'localhost:21403']
        labels:
          group: 'msg-transfer'
       
 

      - targets: [ 'localhost:22500' ]
        labels:
          group: 'task'
      
      - targets: [ 'localhost:22600' ]
        labels:
          group: 'ens'

      - targets: [ 'localhost:22700' ]
        labels:
          group: 'order'

    - job_name: 'node'
      scrape_interval: 8s
      static_configs:
        - targets: [ 'localhost:9100' ]

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - localhost:9093

rule_files:
  - "/etc/prometheus/rules/*rules.yml"
