// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.8
// source: kafkamessage/message.proto

package kafkaMessage

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KafkaMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageType int32         `protobuf:"varint,1,opt,name=MessageType,proto3" json:"MessageType,omitempty"`
	EmailMsg    *EmailMessage `protobuf:"bytes,2,opt,name=emailMsg,proto3" json:"emailMsg,omitempty"`
	SmsMsg      *SmsMessage   `protobuf:"bytes,3,opt,name=smsMsg,proto3" json:"smsMsg,omitempty"`
}

func (x *KafkaMsg) Reset() {
	*x = KafkaMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kafkamessage_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KafkaMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KafkaMsg) ProtoMessage() {}

func (x *KafkaMsg) ProtoReflect() protoreflect.Message {
	mi := &file_kafkamessage_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KafkaMsg.ProtoReflect.Descriptor instead.
func (*KafkaMsg) Descriptor() ([]byte, []int) {
	return file_kafkamessage_message_proto_rawDescGZIP(), []int{0}
}

func (x *KafkaMsg) GetMessageType() int32 {
	if x != nil {
		return x.MessageType
	}
	return 0
}

func (x *KafkaMsg) GetEmailMsg() *EmailMessage {
	if x != nil {
		return x.EmailMsg
	}
	return nil
}

func (x *KafkaMsg) GetSmsMsg() *SmsMessage {
	if x != nil {
		return x.SmsMsg
	}
	return nil
}

type SmsMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SmsType     int32  `protobuf:"varint,1,opt,name=smsType,proto3" json:"smsType,omitempty"`
	Area        string `protobuf:"bytes,2,opt,name=area,proto3" json:"area,omitempty"`
	PhoneNumber string `protobuf:"bytes,3,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	Code        string `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *SmsMessage) Reset() {
	*x = SmsMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kafkamessage_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SmsMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SmsMessage) ProtoMessage() {}

func (x *SmsMessage) ProtoReflect() protoreflect.Message {
	mi := &file_kafkamessage_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SmsMessage.ProtoReflect.Descriptor instead.
func (*SmsMessage) Descriptor() ([]byte, []int) {
	return file_kafkamessage_message_proto_rawDescGZIP(), []int{1}
}

func (x *SmsMessage) GetSmsType() int32 {
	if x != nil {
		return x.SmsType
	}
	return 0
}

func (x *SmsMessage) GetArea() string {
	if x != nil {
		return x.Area
	}
	return ""
}

func (x *SmsMessage) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *SmsMessage) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type EmailMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EmailType int32  `protobuf:"varint,1,opt,name=emailType,proto3" json:"emailType,omitempty"`
	ToAddress string `protobuf:"bytes,2,opt,name=toAddress,proto3" json:"toAddress,omitempty"` //邮箱地址
	Subject   string `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`     //邮箱主题
	Title     string `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`         //标题
	Body      string `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`           //邮件内容
}

func (x *EmailMessage) Reset() {
	*x = EmailMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kafkamessage_message_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmailMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailMessage) ProtoMessage() {}

func (x *EmailMessage) ProtoReflect() protoreflect.Message {
	mi := &file_kafkamessage_message_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailMessage.ProtoReflect.Descriptor instead.
func (*EmailMessage) Descriptor() ([]byte, []int) {
	return file_kafkamessage_message_proto_rawDescGZIP(), []int{2}
}

func (x *EmailMessage) GetEmailType() int32 {
	if x != nil {
		return x.EmailType
	}
	return 0
}

func (x *EmailMessage) GetToAddress() string {
	if x != nil {
		return x.ToAddress
	}
	return ""
}

func (x *EmailMessage) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *EmailMessage) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *EmailMessage) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

var File_kafkamessage_message_proto protoreflect.FileDescriptor

var file_kafkamessage_message_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x6b, 0x61, 0x66, 0x6b, 0x61, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2f, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x6b, 0x61,
	0x66, 0x6b, 0x61, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x96, 0x01, 0x0a, 0x08, 0x6b,
	0x61, 0x66, 0x6b, 0x61, 0x4d, 0x73, 0x67, 0x12, 0x20, 0x0a, 0x0b, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x36, 0x0a, 0x08, 0x65, 0x6d, 0x61,
	0x69, 0x6c, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6b, 0x61,
	0x66, 0x6b, 0x61, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x45, 0x6d, 0x61, 0x69, 0x6c,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x08, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x4d, 0x73,
	0x67, 0x12, 0x30, 0x0a, 0x06, 0x73, 0x6d, 0x73, 0x4d, 0x73, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x18, 0x2e, 0x6b, 0x61, 0x66, 0x6b, 0x61, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x2e, 0x53, 0x6d, 0x73, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x06, 0x73, 0x6d, 0x73,
	0x4d, 0x73, 0x67, 0x22, 0x70, 0x0a, 0x0a, 0x53, 0x6d, 0x73, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x6d, 0x73, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x07, 0x73, 0x6d, 0x73, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x61,
	0x72, 0x65, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x72, 0x65, 0x61, 0x12,
	0x20, 0x0a, 0x0b, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x8e, 0x01, 0x0a, 0x0c, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x54,
	0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x65, 0x6d, 0x61, 0x69, 0x6c,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x6f, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x6f, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x42, 0x10, 0x5a, 0x0e, 0x2e, 0x2f, 0x6b, 0x61, 0x66, 0x6b,
	0x61, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_kafkamessage_message_proto_rawDescOnce sync.Once
	file_kafkamessage_message_proto_rawDescData = file_kafkamessage_message_proto_rawDesc
)

func file_kafkamessage_message_proto_rawDescGZIP() []byte {
	file_kafkamessage_message_proto_rawDescOnce.Do(func() {
		file_kafkamessage_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_kafkamessage_message_proto_rawDescData)
	})
	return file_kafkamessage_message_proto_rawDescData
}

var file_kafkamessage_message_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_kafkamessage_message_proto_goTypes = []interface{}{
	(*KafkaMsg)(nil),     // 0: kafkaMessage.kafkaMsg
	(*SmsMessage)(nil),   // 1: kafkaMessage.SmsMessage
	(*EmailMessage)(nil), // 2: kafkaMessage.EmailMessage
}
var file_kafkamessage_message_proto_depIdxs = []int32{
	2, // 0: kafkaMessage.kafkaMsg.emailMsg:type_name -> kafkaMessage.EmailMessage
	1, // 1: kafkaMessage.kafkaMsg.smsMsg:type_name -> kafkaMessage.SmsMessage
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_kafkamessage_message_proto_init() }
func file_kafkamessage_message_proto_init() {
	if File_kafkamessage_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_kafkamessage_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KafkaMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kafkamessage_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SmsMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kafkamessage_message_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmailMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kafkamessage_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kafkamessage_message_proto_goTypes,
		DependencyIndexes: file_kafkamessage_message_proto_depIdxs,
		MessageInfos:      file_kafkamessage_message_proto_msgTypes,
	}.Build()
	File_kafkamessage_message_proto = out.File
	file_kafkamessage_message_proto_rawDesc = nil
	file_kafkamessage_message_proto_goTypes = nil
	file_kafkamessage_message_proto_depIdxs = nil
}
