// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: kafkamessage/message.proto

package kafkaMessage

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on KafkaMsg with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *KafkaMsg) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on KafkaMsg with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in KafkaMsgMultiError, or nil
// if none found.
func (m *KafkaMsg) ValidateAll() error {
	return m.validate(true)
}

func (m *KafkaMsg) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetMessageType() <= 0 {
		err := KafkaMsgValidationError{
			field:  "MessageType",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetEmailMsg()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, KafkaMsgValidationError{
					field:  "EmailMsg",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, KafkaMsgValidationError{
					field:  "EmailMsg",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetEmailMsg()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return KafkaMsgValidationError{
				field:  "EmailMsg",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetSmsMsg()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, KafkaMsgValidationError{
					field:  "SmsMsg",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, KafkaMsgValidationError{
					field:  "SmsMsg",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetSmsMsg()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return KafkaMsgValidationError{
				field:  "SmsMsg",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return KafkaMsgMultiError(errors)
	}

	return nil
}

// KafkaMsgMultiError is an error wrapping multiple validation errors returned
// by KafkaMsg.ValidateAll() if the designated constraints aren't met.
type KafkaMsgMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m KafkaMsgMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m KafkaMsgMultiError) AllErrors() []error { return m }

// KafkaMsgValidationError is the validation error returned by
// KafkaMsg.Validate if the designated constraints aren't met.
type KafkaMsgValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e KafkaMsgValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e KafkaMsgValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e KafkaMsgValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e KafkaMsgValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e KafkaMsgValidationError) ErrorName() string { return "KafkaMsgValidationError" }

// Error satisfies the builtin error interface
func (e KafkaMsgValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sKafkaMsg.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = KafkaMsgValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = KafkaMsgValidationError{}

// Validate checks the field values on SmsMessage with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *SmsMessage) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SmsMessage with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in SmsMessageMultiError, or
// nil if none found.
func (m *SmsMessage) ValidateAll() error {
	return m.validate(true)
}

func (m *SmsMessage) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for SmsType

	// no validation rules for Area

	// no validation rules for PhoneNumber

	// no validation rules for Code

	if len(errors) > 0 {
		return SmsMessageMultiError(errors)
	}

	return nil
}

// SmsMessageMultiError is an error wrapping multiple validation errors
// returned by SmsMessage.ValidateAll() if the designated constraints aren't met.
type SmsMessageMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SmsMessageMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SmsMessageMultiError) AllErrors() []error { return m }

// SmsMessageValidationError is the validation error returned by
// SmsMessage.Validate if the designated constraints aren't met.
type SmsMessageValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SmsMessageValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SmsMessageValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SmsMessageValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SmsMessageValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SmsMessageValidationError) ErrorName() string { return "SmsMessageValidationError" }

// Error satisfies the builtin error interface
func (e SmsMessageValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSmsMessage.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SmsMessageValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SmsMessageValidationError{}

// Validate checks the field values on EmailMessage with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *EmailMessage) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on EmailMessage with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in EmailMessageMultiError, or
// nil if none found.
func (m *EmailMessage) ValidateAll() error {
	return m.validate(true)
}

func (m *EmailMessage) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for EmailType

	// no validation rules for ToAddress

	// no validation rules for Subject

	// no validation rules for Title

	// no validation rules for Body

	if len(errors) > 0 {
		return EmailMessageMultiError(errors)
	}

	return nil
}

// EmailMessageMultiError is an error wrapping multiple validation errors
// returned by EmailMessage.ValidateAll() if the designated constraints aren't met.
type EmailMessageMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m EmailMessageMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m EmailMessageMultiError) AllErrors() []error { return m }

// EmailMessageValidationError is the validation error returned by
// EmailMessage.Validate if the designated constraints aren't met.
type EmailMessageValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e EmailMessageValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e EmailMessageValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e EmailMessageValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e EmailMessageValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e EmailMessageValidationError) ErrorName() string { return "EmailMessageValidationError" }

// Error satisfies the builtin error interface
func (e EmailMessageValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sEmailMessage.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = EmailMessageValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = EmailMessageValidationError{}
